DROP TABLE IF EXISTS "investments" CASCADE;
DROP TABLE IF EXISTS "savings_goals" CASCADE;
DROP TABLE IF EXISTS "budgets" CASCADE;
DROP TABLE IF EXISTS "transactions" CASCADE;
DROP TABLE IF EXISTS "categories" CASCADE;
DROP TABLE IF EXISTS "accounts" CASCADE;
DROP TABLE IF EXISTS "users" CASCADE;

DROP TYPE IF EXISTS "investment_types" CASCADE;
DROP TYPE IF EXISTS "period_type" CASCADE;
DROP TYPE IF EXISTS "transaction_type" CASCADE;
DROP TYPE IF EXISTS "category_type" CASCADE;
DROP TYPE IF EXISTS "account_type" CASCADE;

