services:
  db:
    image: postgres:16.3
    container_name: go-api-template-db
    environment:
      POSTGRES_DB: go-api-template
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"

volumes:
  db-data:
